# Generated by Django 4.2.6 on 2023-10-10 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nam',
            fields=[
                ('name_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_val', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patronymic',
            fields=[
                ('pat_id', models.AutoField(primary_key=True, serialize=False)),
                ('pat_val', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='street',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('st_val', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='surname',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_val', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('nb_hs', models.CharField(max_length=100)),
                ('ph_nb', models.CharField(max_length=100)),
                ('patronymic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patronymic')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.street')),
                ('surname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.surname')),
            ],
        ),
    ]
