# Generated by Django 4.2.6 on 2023-10-10 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_main_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nam'),
        ),
        migrations.AlterField(
            model_name='main',
            name='nb_hs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='patronymic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.patronymic'),
        ),
        migrations.AlterField(
            model_name='main',
            name='ph_nb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='street',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.street'),
        ),
        migrations.AlterField(
            model_name='main',
            name='surname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.surname'),
        ),
    ]
