# Generated by Django 4.2.6 on 2023-10-23 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_main_name_alter_main_patronymic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.nam'),
        ),
        migrations.AlterField(
            model_name='main',
            name='patronymic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.patronymic'),
        ),
        migrations.AlterField(
            model_name='main',
            name='street',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.street'),
        ),
        migrations.AlterField(
            model_name='main',
            name='surname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.surname'),
        ),
    ]
