# Generated by Django 4.2.6 on 2023-10-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_main_name_alter_main_patronymic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='building',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='flat',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
