# Generated by Django 4.2.5 on 2023-10-19 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fam',
            fields=[
                ('id_fam', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fam', models.CharField(max_length=50, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Nam',
            fields=[
                ('id_name', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Otchestvo',
            fields=[
                ('id_otch', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('otch', models.CharField(max_length=100, verbose_name='Отчество')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id_street', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150, verbose_name='Улица')),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('bldn', models.CharField(max_length=15, verbose_name='Номер здания')),
                ('bldn_k', models.CharField(max_length=15, verbose_name='Корпус')),
                ('appr', models.PositiveSmallIntegerField(verbose_name='Квартира')),
                ('tel', models.CharField(max_length=25, verbose_name='Телефон')),
                ('fam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.fam')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nam')),
                ('otch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.otchestvo')),
                ('street', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.street')),
            ],
        ),
    ]
