# Generated by Django 4.2.5 on 2023-10-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fam',
            name='fam',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fam',
            name='id_fam',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='main',
            name='appr',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='bldn',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='main',
            name='bldn_k',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='main',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='main',
            name='tel',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='nam',
            name='id_name',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nam',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='otchestvo',
            name='id_otch',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otchestvo',
            name='otch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='street',
            name='id_street',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='street',
            name='street',
            field=models.CharField(max_length=150),
        ),
    ]
