# Generated by Django 4.2.5 on 2023-11-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_session_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_token',
            field=models.CharField(blank=True, default='session_token', max_length=50),
        ),
    ]
